version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.rootless
    ports:
      - "8080:8080"
    environment:
      - BASE_URL=https://www.tiepphan.com
      - BASE_PATH=/
